extend doc for operator
kokuwaio/rabbitmq-operator pull request #10
Opened 2020-12-15 13:23 UTC by rpahli

2020-12-15 14:07 UTC, axdotl requested changes

2020-12-15 14:07 UTC, axdotl commented on README.md
> +This is a operator which handles rabbitmq resources via kubernetes custom resource definitions. To manage rabbitmq clsuters you can use for example the [rabbitmq operator](https://github.com/rabbitmq
```suggestion
This is a operator which handles rabbitmq resources via kubernetes custom resource definitions.
To manage rabbitmq clusters you can use the [rabbitmq operator](https://github.com/rabbitmq/cluster-operator) for instance.
```

2020-12-15 14:07 UTC, axdotl commented on README.md
> +### creating a cluster reference
```suggestion
### Creating a Cluster Reference
```

2020-12-15 14:07 UTC, axdotl commented on README.md
> +### creating a user
```suggestion
### Creating a User
```

2020-12-15 14:07 UTC, axdotl commented on README.md
> +### creating a queue
```suggestion
### Creating a Queue
```

2020-12-18 14:45 UTC, monotek approved these changes

2020-12-18 18:18 UTC, merged